services:
  - type: web
    name: ramsfx-license-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: PAYPAL_LINKS
        sync: false
